name: Compile paper

# Provide permissions to read and write the repo, create releases.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: write-all

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-texlive-latest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./document

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Install just
      run: |
        sudo apt-get update
        sudo apt-get install -y just

    - name: Create .latexminted_config file
      run: |
        bash ./tools/create_latexminted_config.sh
        just latexminted_config

    # Uses the latest TeXLive distribution (currently with minted v3+)
    - name: Compile paper
    - uses: xu-cheng/texlive-action@v3
      with:
        run: |
          latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode paper.tex


    # Uses the latest TeXLive distribution (currently with minted v3+)
    - name: Compile submission
      uses: xu-cheng/latex-action@master
      with:
        root_file: ./document/submission.tex

    - name: Release
      if: ${{ github.event_name == 'push' }}
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.run_number }}
        tag_name: release-${{ github.run_number }}
        files: |
          paper.pdf
          submission.pdf
  build-texlive-2024:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./document

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Install just
      run: |
        sudo apt-get update
        sudo apt-get install -y just

    # Uses an older TeXLive distribution (with minted v2.9)
    - name: Compile paper
      uses: xu-cheng/latex-action@master
      with:
        docker_image: ghcr.io/xu-cheng/texlive-full:20240901
        root_file: ./document/paper.tex

    # Uses an older TeXLive distribution (with minted v2.9)
    - name: Compile submission
      uses: xu-cheng/latex-action@master
      with:
        docker_image: ghcr.io/xu-cheng/texlive-full:20240901
        root_file: ./document/submission.tex