name: Compile paper

# Provide permissions to read and write the repo, create releases.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: write-all

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-texlive-latest:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Install just
      run: |
        sudo apt-get update
        sudo apt-get install -y just

    - name: Create .latexminted_config file
      run: |
        cd document
        bash ./tools/create_latexminted_config.sh
        just latexminted_config

    - name: Compile paper
      uses: xu-cheng/latex-action@v4
      with:
        root_file: paper.tex
        working_directory: document

    - name: Compile submission
      uses: xu-cheng/latex-action@v4
      with:
        root_file: submission.tex
        working_directory: document

    - name: Release
      if: ${{ github.event_name == 'push' }}
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.run_number }}
        tag_name: release-${{ github.run_number }}
        files: |
          document/paper.pdf
          document/submission.pdf
